#Configuration
VERBOSE: False
MODEL:
  MODE: 'DeFlare'
# Optimization arguments.
TRAINOPTIM:
  BATCH: 16 # origin: 2
  EPOCHS: 300
  # NEPOCH_DECAY: [10]
  LR_INITIAL: 1e-4 #origin: 2e-4
  LR_MIN: 1e-7 # origin: 1e-6
  # BETA1: 0.9
TRAINING:
  VAL_AFTER_EVERY: 1
  RESUME: False
  TRAIN_PS: 256 # origin: 256
  VAL_PS: 512
  #TRAIN_DIR: '/data/zbl/deflare/FlareDataSet2/SmallTrain'       # path to training data
  TRAIN_DIR: '/mnt/sdb/zbl/FlareDataSet4/train'       # path to training data
  VAL_DIR: '/mnt/sdb/zbl/FlareDataSet2/test/synthetic'
  SAVE_DIR: './checkpoints'           # path to save models and images
TESTING:
  TEST_PS: None
  TEST_DIR: '/mnt/sdb/zbl/FlareDataSet2/test/real' # path to validation data
  TEST_DIR_SYN: '/mnt/sdb/zbl/FlareDataSet2/test/synthetic' # path to validation data
  WEIGHT_ROOT: './checkpoints/DeFlare/models'
  WEIGHT_NAME: '/model_bestPSNR.pth'
